### ISSUE TITLE
Are you going to continue support of this project?

### ISSUE THREAD

**Issue by rgordeev** [marsbits/restfbmessenger#10]
Hello! Your spring-boot-starter is great, but I would like to know are you going to support latest versions of the resfb client and facebook messenger API?

**Comment by marceloverdijk** [comment]
Hi @rgordeev, I'm in close contact with @nbartels about the next release of restfb.
After it's released I'm going to upgrade this lib to the latest Messenger Platform features.

**Comment by rgordeev** [comment]
@marceloverdijk Thanks for your answer! Great news! ;)

**Comment by marceloverdijk** [comment]
Just release v2.2.0.
If you find any issue or missing functionality please create a new issue.
