### ISSUE TITLE
Invalid expected signature generated for payload which contains percentage %

### ISSUE THREAD

**Issue by reyjexter** [marsbits/restfbmessenger#11]
There seems to be a bug which when server receives a message with payload that contains % character, the expected signature doesn't match with header signature.

This happens for example on:

- Location quick reply which contains 
- When you reply "I got it %"

When replying with "I got it" without the percentange, this works correctly and signature generated matches with the one on header.

Any help is appreciated. Thanks

**Comment by reyjexter** [comment]
Sorry, this isn't really a bug with restfbmessenger after all but more like MVC framework related which sometimes the response body is being parsed automatically. The correct fix is to parse the response body as UTF-8 which should include \u characters.

In our case, we were using Play Framework 2.3 which the framework provides an automatic way to parse content based on given type so using .asJson() didn't work but parsing the raw content and converting to UTF-8 manually fixed the problem.

Example solution
```
@BodyParser.Of(BodyParser.Raw.class)
public Result webhookPost() {
     final String body= new String(request().body().asRaw().asBytes(), "UTF-8");
}
```

**Comment by marceloverdijk** [comment]
~~Would you be able to provide a stacktrace?~~

Thanks for further feedback!
